# Baseline Model Development

## Import the Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

## Load the Dataset

In [2]:
dataset = pd.read_csv('Datasets/final_dataset.csv')
dataset.head()

Disease  Symptom_1  Symptom_2  Symptom_3  Symptom_4  Symptom_5  Symptom_6  \
0       15          0          1         34         55         14         42   
1       15          1         34         55         33         14         42   
2       15          0         34         55         33         14         42   
3       15          0          1         55         33         14         42   
4       15          0          1         34         33         14         42   

   Symptom_7  Symptom_8  Symptom_9  Symptom_10  
0         43         43         79          79  
1         43         43         79          79  
2         43         43         79          79  
3         43         43         79          79  
4         43         43         79          79

## Feature Selection

In [3]:
X = dataset.iloc[:, 1:].values
y = dataset['Disease'].values

## Split the dataset into training and testing sets

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Standardize the features for SVM models.

In [5]:
scalar = StandardScaler()
X_train_scaled = scalar.fit_transform(X_train)
X_test_scaled = scalar.fit_transform(X_test)

## Model Development
### Initialize and train various classifiers.

### Logistic Regression

In [6]:
log_model = LogisticRegression(multi_class='ovr', solver='liblinear')
log_model.fit(X_train, y_train)

c:\Users\PRANAV\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr', solver='liblinear')

In [7]:
log_y_pred = log_model.predict(X_test)

### KNN Classifier

In [8]:
knn_model = KNeighborsClassifier(n_neighbors=5, metric = 'minkowski', p = 2)
knn_model.fit(X_train,y_train)

KNeighborsClassifier()

In [9]:
knn_y_pred = knn_model.predict(X_test)

### SVM Classifier

In [10]:
svm_model = SVC(kernel='linear', random_state=0)
svm_model.fit(X_train_scaled, y_train)

SVC(kernel='linear', random_state=0)

In [11]:
svm_y_pred = svm_model.predict(X_test)

### Kernal SVM Classifier

In [12]:
kernal_svm_model = SVC(kernel='rbf', random_state=0)
kernal_svm_model.fit(X_train_scaled, y_train)

SVC(random_state=0)

In [13]:
kernal_svm_y_pred = kernal_svm_model.predict(X_test)

### Naive Bayes Classifier

In [14]:
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)

GaussianNB()

In [15]:
nb_y_pred = nb_model.predict(X_test)

### Decision Tree Classifier

In [16]:
dec_tree_model = DecisionTreeClassifier()
dec_tree_model.fit(X_train, y_train)

DecisionTreeClassifier()

In [17]:
dec_tree_y_pred = dec_tree_model.predict(X_test)

### Random Forest Classifier

In [18]:
ran_forest_model = RandomForestClassifier()
ran_forest_model.fit(X_train, y_train)

RandomForestClassifier()

In [19]:
ran_forest_y_pred = ran_forest_model.predict(X_test)

## Evaluate Models
### Function to calculate and print evaluation metrics for a given model.

In [20]:
def evaluate_model(y_test, y_pred, model_name):
    print(f"\n{model_name} Evaluation Metrics:")
    print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
    print(f"Precision: {precision_score(y_test, y_pred, average='weighted'):.4f}")
    print(f"Recall: {recall_score(y_test, y_pred, average='weighted'):.4f}")
    print(f"F1 Score: {f1_score(y_test, y_pred, average='weighted'):.4f}")
    print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}")

### Evaluate each model

In [21]:
evaluate_model(y_test, log_y_pred, "Logistic Regression")


Logistic Regression Evaluation Metrics:
Accuracy: 0.8404
Precision: 0.8597
Recall: 0.8404
F1 Score: 0.8423
Confusion Matrix:
[[ 8  0  0 ...  0  0  0]
 [ 0 20  0 ...  0  0  0]
 [ 0  0 20 ...  2  0  0]
 ...
 [ 0  0  0 ... 26  0  0]
 [ 0  0  0 ...  0 19  0]
 [ 0  0  0 ...  0  0 28]]


In [22]:
evaluate_model(y_test, knn_y_pred, "K-Nearest Neighbors")


K-Nearest Neighbors Evaluation Metrics:
Accuracy: 0.9919
Precision: 0.9924
Recall: 0.9919
F1 Score: 0.9918
Confusion Matrix:
[[18  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  0 24 ...  0  0  0]
 ...
 [ 0  0  0 ... 26  0  0]
 [ 0  0  0 ...  0 22  0]
 [ 0  0  0 ...  0  0 34]]


In [23]:
evaluate_model(y_test, svm_y_pred, "SVM (Linear Kernel")


SVM (Linear Kernel Evaluation Metrics:
Accuracy: 0.0234
Precision: 0.0012
Recall: 0.0234
F1 Score: 0.0020
Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


c:\Users\PRANAV\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [24]:
evaluate_model(y_test, kernal_svm_y_pred, "SVM (RBF Kernel)")


SVM (RBF Kernel) Evaluation Metrics:
Accuracy: 0.0244
Precision: 0.0006
Recall: 0.0244
F1 Score: 0.0012
Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


c:\Users\PRANAV\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [25]:
evaluate_model(y_test, nb_y_pred, "Naive Bayes")


Naive Bayes Evaluation Metrics:
Accuracy: 0.8364
Precision: 0.8819
Recall: 0.8364
F1 Score: 0.8435
Confusion Matrix:
[[ 8  0  0 ...  0  0  0]
 [ 0 22  8 ...  0  0  0]
 [ 0  0 22 ...  2  0  0]
 ...
 [ 0  0  0 ... 26  0  0]
 [ 9  0  0 ...  0  9  0]
 [ 0  0  0 ...  0  0 30]]


In [26]:
evaluate_model(y_test, dec_tree_y_pred, "Decision Tree")


Decision Tree Evaluation Metrics:
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1 Score: 1.0000
Confusion Matrix:
[[18  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  0 24 ...  0  0  0]
 ...
 [ 0  0  0 ... 26  0  0]
 [ 0  0  0 ...  0 22  0]
 [ 0  0  0 ...  0  0 34]]


In [27]:
evaluate_model(y_test, ran_forest_y_pred, "Random Forest")


Random Forest Evaluation Metrics:
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1 Score: 1.0000
Confusion Matrix:
[[18  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  0 24 ...  0  0  0]
 ...
 [ 0  0  0 ... 26  0  0]
 [ 0  0  0 ...  0 22  0]
 [ 0  0  0 ...  0  0 34]]


## Compare Model Performance

In [28]:
models = pd.DataFrame(
    {
        'Classifier': ['Logistic Regression', 'K-Nearest Neighbors', 'SVM (Linear Kernel)', 'SVM (RBF Kernel)',
                       'Naive Bayes', 'Decision Tree', 'Random Forest'],
        'Accuracy': [
            accuracy_score(y_test, log_y_pred),
            accuracy_score(y_test, knn_y_pred),
            accuracy_score(y_test, svm_y_pred),
            accuracy_score(y_test, kernal_svm_y_pred),
            accuracy_score(y_test, nb_y_pred),
            accuracy_score(y_test, dec_tree_y_pred),
            accuracy_score(y_test, ran_forest_y_pred)
        ]
    }
)

In [29]:
models.sort_values(by='Accuracy', ascending=False)

Classifier  Accuracy
5        Decision Tree  1.000000
6        Random Forest  1.000000
1  K-Nearest Neighbors  0.991870
0  Logistic Regression  0.840447
4          Naive Bayes  0.836382
3     SVM (RBF Kernel)  0.024390
2  SVM (Linear Kernel)  0.023374